### PR TITLE
[RUN-2965] Properly re-initialize `gReplayScript` (and its dependencies) where necessary

### PR DESCRIPTION
**Pull request by Domiii**
* paired w/ https://github.com/replayio/chromium-v8/pull/206
* https://linear.app/replay/issue/RUN-2965/-record-replay-and-other-replay-only-props-are-not-available-after
* Tests:
  * [Live tests](https://buildkite.com/replay/testing-runtime-e2e/builds/2157): ✅ (and no recorder crashes)
    * [Live tests re-run](https://buildkite.com/replay/testing-runtime-e2e/builds/2158):  ✅ (and no recorder crashes)
  * [FE](https://buildkite.com/replay/runtime-fe-end-to-end-tests/builds/52#018cdb35-b598-4b1c-a40e-5f0be21770c9): ✅
    * [FE re-run](https://buildkite.com/replay/runtime-fe-end-to-end-tests/builds/54#018cdbb7-88ad-4f99-8fae-f8a73bf04422): ✅
  * Spot check: [src](https://github.com/replayio/backend/pull/9239/files#diff-889527a7a6533312177fc7a9c606ed65ea618fa16e04fc108366bb0999b1d015R1) ✅ -
      ```
      $ npm test -- dynamic_websites/run-2965.spec.ts

      > runtime-tests@0.0.1 test
      > npx playwright test --config=playwright.config.ts dynamic_websites/run-2965.spec.ts


      Running 1 test using 1 worker
      [chromium] › dynamic_websites/run-2965.spec.ts:18:5 › [RUN-2965] Use Replay API after Reload
      Starting RUNTIME test-http-server...
      Runtime Test Server running on port 3456.
        1 passed (2.0s)
      ```

### CODE REVIEW

**Review by jasonLaster — COMMENTED** [review]
Out of curiosity, how did you test the change?

**Comment by Domiii** [comment]
@jasonLaster 
> Out of curiosity, how did you test the change?

This is just untested WIP.

But to answer a slightly different question: "How will you test this change?"

Answer:

1. Spot checking with the test I mentioned in the issue [here](https://linear.app/replay/issue/RUN-2965/-record-replay-and-other-replay-only-props-are-not-available-after#comment-f75d40f6) which have been enabled by RUN-3065. I am still considering some other scenarios I also want to test, specifically with an eye on RUN-3009. I am looking forward to adding them to our CI moving forward.
2. Our CI currently only has static live tests at its disposal.

Past + Future options:
1. We used to run Metabase tests upon merge-to-master but those are out of capacity due to RUN-3072, I guess.
2. FE E2E tests are not fully integrated yet.

Good thing we are fixing all that moving forward. Will be in that planning doc.

**Comment by jasonLaster** [comment]
Makes sense

**Comment by Domiii** [comment]
@jasonLaster I forgot to mention another tool in our testing toolbox that I'm using here:

[This patch](https://github.com/replayio/chromium/pull/1052/commits/6b51c7ce0c4fe6016abadb19466989c275d2edb0) modifies Buildkite files to change the platforms that tests run on, building and using of a custom driver/linker and more. That's enabled by [RUN-2814](https://linear.app/replay/issue/RUN-2814/buildkite-manipulation-script-to-run-custom-commands-on-selected).

**Comment by Domiii** [comment]
* Re-adding reviewers after making sure that recorder crashes are under control.
* [FE E2E tests](https://buildkite.com/replay/runtime-fe-end-to-end-tests/builds/52#018cdb35-b598-4b1c-a40e-5f0be21770c9) also look good (only 2 failures, same as other recent runs), but I'm re-running for extra safety.

**Review by bhackett1024 — APPROVED** [review]

**Comment by Domiii** [comment]
FE E2E tests still looking good after V8 patch merge. Merging.

**Pull request merged**
