### PR TITLE
Ensure WaitableEvent::WaitMany doesn't return until the corresponding…

### PR DESCRIPTION
**Pull request by bhackett1024**
… event was signaled on macOS

https://linear.app/replay/issue/RUN-1547

### CODE REVIEW

**Review by kannanvijayan — APPROVED** [review]
Stamping, but confused.  `RecordReplayEnsureOrdered` just takes an ordered lock and releases it.  Presumably this enforces ordering with respect to some other piece of code that's also taking the lock?

Some comments around these functions to indicate what other place it's synchronizing with would be helpful, otherwise they just look like dark magic invocations.

**Comment by kannanvijayan** [comment]
Presumably this is synchronizing with `WaitableEvent::Signal`?

**Comment by bhackett1024** [comment]
@kannanvijayan I'll update the comment, but there is information about what this is fixing in the linked linear ticket: https://linear.app/replay/issue/RUN-1547#comment-573a69e4

**Comment by bhackett1024** [comment]
Actually RecordReplayEnsureOrdered already has a good comment.

**Pull request merged**
