### PR TITLE
Narrower asserts in `NGInlineNode::ShapeTextIncludingFirstLine`

### PR DESCRIPTION
**Pull request by kannanvijayan**
For #RUN-1261 (https://linear.app/replay/issue/RUN-1261/add-counter-to-nginlinenode-and-assert-in-shapetextincludingfirstline)

### CODE REVIEW

**Review by bhackett1024 — CHANGES_REQUESTED** [review]
Counting things this way isn't going to help.  Since we always assert here already that is already counting the calls.  FontFallbackList::DeterminePrimarySimpleFontData needs an assertion so we can convert this to a regular mismatch, see https://linear.app/replay/issue/RUN-1219#comment-eb6185af

**Comment by kannanvijayan** [comment]
Fixed up the assertions here to get at the control flow path that leads into the `Shape` call.

**Review by bhackett1024 — CHANGES_REQUESTED** [review]
FontFallbackList::DeterminePrimarySimpleFontData needs an assertion so we can convert this to a regular mismatch

**Comment by kannanvijayan** [comment]
> Fixed up the assertions here to get at the control flow path that leads into the `Shape` call.

We've added asserts in the control flow leading up to this, so that should already be the case, but I'll be explicit and add this too.

**Review by bhackett1024 — APPROVED** [review]

**Pull request merged**
