### PR TITLE
ability to build in buildkite

### PR DESCRIPTION
**Pull request by jazzdan**

### CODE REVIEW

**Comment by jazzdan** [comment]
Just to connect the dots: this is currently being triggered manually by [this buildkite pipeline](https://buildkite.com/replay/chromium-build), which is defined as:

```yaml
env:
  FORCE_COLOR: 1
  GIT_TERMINAL_PROMPT: 0

steps:
  - label: "Build chromium"
    plugins:
      - thedyrt/skip-checkout#v0.1.1: ~
    command: "PATH=/var/lib/buildkite-agent/depot_tools:$$PATH && goma_ctl restart && cd /var/lib/buildkite-agent/chromium/src && node buildLinux.js"
    env:
      GOMA_SERVER_HOST: simpsonite.goma.engflow.com
      GOMACTL_USE_PROXY: false
    agents:
      - "runtimeType=build"
      - "os=linux"  
```

**Review by klochek — COMMENTED** [review]
This looks good to me, but did you by any chance test out how long a no-op build takes?  I hope the containerization doesn't mean we lose incremental builds--16 minutes for a change I can build on my local machine in 1 could end up being problematic.  (I just tried, and the build died :( https://buildkite.com/replay/chromium-build/builds/44#0186be70-fa68-4dcf-ad7e-0886ec0f7e20)

**Comment by jazzdan** [comment]
@klochek I saw a no-op build take about 2 minutes https://buildkite.com/replay/chromium-build/builds/43

**Comment by jazzdan** [comment]
We shouldn't lose any incrementality because we are using goma distributed builds/build caching via engflow

**Review by klochek — APPROVED** [review]

**Pull request merged**
