### PR TITLE
Always commit paints when recording/replaying.

### PR DESCRIPTION
**Pull request by kannanvijayan**
For #RUN-2434 (kannan/run-2434-chromium-paints-arent-updated-during-scrolls)

When scrolling on simple pages, chromium optimizes things by realizing that a full paint commit doesn't need to be done because the screen update can be handled purely via the compositor.

However, we need the paint commit stage to run to trigger our paint collection callbacks.

### CODE REVIEW

**Comment by bhackett1024** [comment]
This seems like it could have a really bad impact on performance, which is extremely important.  I'd like to hold off on landing this without numbers where we can see the impact on overhead on the metabase benchmark, though we do need to make it easier to get those overhead numbers for a PR.

**Comment by kannanvijayan** [comment]
> This seems like it could have a really bad impact on performance, which is extremely important. I'd like to hold off on landing this without numbers where we can see the impact on overhead on the metabase benchmark, though we do need to make it easier to get those overhead numbers for a PR.

I'll do some local measurements against the metabase suite.

**Comment by kannanvijayan** [comment]
> This seems like it could have a really bad impact on performance, which is extremely important. I'd like to hold off on landing this without numbers where we can see the impact on overhead on the metabase benchmark, though we do need to make it easier to get those overhead numbers for a PR.

Ran some measurements locally against the metabase benchmark, timing just the record portion.  Made sure to run headed to force rendering, and ran against a subset of the tests to reduce time.
```
Command: time yarn test-cypress-run --headed --browser=$REPLAY_DIR/chromium/src/out/Release/chrome --spec e2e/test/scenarios/admin/datamodel

## Test (with patch)
### Run 1
real	8m59.815s
user	33m56.783s
sys	2m21.469s

### Run 2
real	8m57.633s
user	34m4.129s
sys	2m20.790s

## Reference (without patch)
### Run 1
real	8m51.802s
user	33m35.063s
sys	2m20.752s

### Run 2
real	9m24.434s
user	37m25.698s
sys	2m25.734s
```

I'm gonna assume RUN2 of the reference was fluke and a noise.  Overall, this patch doesn't seem to hit recording overhead too hard at all.  I think these hit mostly during scrolls that don't require repaint, which don't happen for long in the recording.  There are not many other operations that would visually update the screen but not require a repaint.

**Comment by bhackett1024** [comment]
Alright, fair enough.

**Review by bhackett1024 — APPROVED** [review]

**Comment by kannanvijayan** [comment]
Only tests that are failing is dynamic nytimes.com, which is failing frequently these days.  Otherwise passing.

**Pull request merged**
