### PR TITLE
RUN-1264: Assert SimpleWatcher's Arm and Cancel

### PR DESCRIPTION
**Pull request by Domiii**
https://linear.app/replay/issue/RUN-1126#comment-064a680c
https://linear.app/replay/issue/RUN-1264/add-asserts-in-arm-and-cancel

### CODE REVIEW

**Review by bhackett1024 — CHANGES_REQUESTED** [review]
The associated issue has a call stack mismatch, the first thing we need to do is convert it to a regular mismatch by adding asserts at the places where the current time is being fetched.

**Comment by Domiii** [comment]
@bhackett1024 
> The associated issue has a call stack mismatch, the first thing we need to do is convert it to a regular mismatch by adding asserts at the places where the current time is being fetched.

Can I keep the other `Assert`s?

**Comment by Domiii** [comment]
> The associated issue has a call stack mismatch, the first thing we need to do is convert it to a regular mismatch by adding asserts at the places where the current time is being fetched.

Can I keep the other `Assert`s?

**Comment by bhackett1024** [comment]
> > The associated issue has a call stack mismatch, the first thing we need to do is convert it to a regular mismatch by adding asserts at the places where the current time is being fetched.
> 
> Can I keep the other `Assert`s?

Sure

**Review by bhackett1024 — CHANGES_REQUESTED** [review]
I don't think this patch does what I asked for in my last review.  Can you paste or link the mismatch you are trying to address with this?

**Comment by Domiii** [comment]
@bhackett1024
* Forgot to mention in previous message: I addressed your comment already sent out a re-invite.
* But I just also fixed a typo.

Feel free to re-review. Explanations here: https://linear.app/replay/issue/RUN-1126/mismatch-simplewatchercontextcallnotify#comment-064a680c

**Comment by Domiii** [comment]
> I don't think this patch does what I asked for in my last review. Can you paste or link the mismatch you are trying to address with this?

I always add most relevant links to the description.
Here you go: https://linear.app/replay/issue/RUN-1126#comment-064a680c

**Comment by Domiii** [comment]
> > I don't think this patch does what I asked for in my last review. Can you paste or link the mismatch you are trying to address with this?

(@bhackett1024, forgot to tag - tagging you here explicitely, just to increase chances of notifications working)

**Comment by bhackett1024** [comment]
I saw the links in the description, but nothing in that issue seems to have anything to do with these asserts.  This is the call stack mismatch I saw, and which this patch does not deal with:

```
  "processNonFatal": {
    "why": "RecordedCallStackMismatch",
    "name": "clock_gettime",
    "threadId": 1,
    "recordedStack": [
      "base::subtle::TimeTicksNowIgnoringOverride()+34",
      "base::sequence_manager::internal::TaskQueueImpl::PostImmediateTaskImpl(base::sequence_manager::internal::PostedTask,.base::sequence_manager::internal::TaskQueueImpl::CurrentThread)+291",
      "base::sequence_manager::internal::TaskQueueImpl::PostTask(base::sequence_manager::internal::PostedTask)+123",
      "base::sequence_manager::internal::TaskQueueImpl::GuardedTaskPoster::PostTask(base::sequence_manager::internal::PostedTask)+226",
      "base::sequence_manager::internal::TaskQueueImpl::TaskRunner::PostDelayedTask(base::Location.const&,.base::OnceCallback<void.()>,.base::TimeDelta)+186",
      "base::TaskRunner::PostTask(base::Location.const&,.base::OnceCallback<void.()>)+39",
      "mojo::SimpleWatcher::Context::Notify(unsigned.int,.MojoHandleSignalsState,.unsigned.int)+511",
      "mojo::SimpleWatcher::Context::CallNotify(MojoTrapEvent.const*)+32"
    ],
    "replayedStack": [
      "base::subtle::TimeTicksNowIgnoringOverride()+34",
      "blink::Event::Event(WTF::AtomicString.const&,.blink::Event::Bubbles,.blink::Event::Cancelable,.blink::Event::ComposedMode)+34",
      "blink::XMLHttpRequest::DispatchReadyStateChangeEvent()+265",
      "blink::XMLHttpRequest::DidReceiveData(char.const*,.unsigned.int)+86",
      "blink::Resource::NotifyDataReceived(char.const*,.unsigned.long)+179",
      "blink::Resource::AppendData(char.const*,.unsigned.long)+95",
      "blink::ResourceLoader::DidReceiveData(char.const*,.int)+558",
      "blink::ResponseBodyLoader::OnStateChange()+759"
    ]
  },
```

**Comment by Domiii** [comment]
> This is the call stack mismatch I saw, and which this patch does not deal with: ...

We are asserting on `ResponseBodyLoader::OnStateChange`. I am also explaining the logic of the other `Assert`s.

But Ok, I'll (i) discuss w/ Kannan on Mon, and also I'll (ii) keep a reference to this. If still necessary, I'll bring it up on Tue.

**Comment by bhackett1024** [comment]
There are eight or so frames between ResponseBodyLoader::OnStateChange and the call that triggered the call stack mismatch.  We need to have an assertion right at the TimeTicksNowIgnoringOverride(), or as close as is reasonably possible (and such that the time will be definitely be read right after the assertion).  In this case that would be XMLHttpRequest::DispatchReadyStateChangeEvent

**Comment by bhackett1024** [comment]
I think TaskQueueImpl::PostImmediateTaskImpl also needs an assertion, though it's hard to tell because github is loading very slowly for me.

**Comment by Domiii** [comment]
@bhackett1024 

> In this case that would be XMLHttpRequest::DispatchReadyStateChangeEvent

Done.

> I think TaskQueueImpl::PostImmediateTaskImpl also needs an assertion, though it's hard to tell because github is loading very slowly for me.

I added one there as well (it did not have an `Assert` yet).

>  nothing in that issue seems to have anything to do with these asserts

Is it not reasonable to assume that `CallNotify` never got hit because its trap was deleted non-deterministically? That is why I added an assert to trap removal :shrug:

**Review by bhackett1024 — APPROVED** [review]
Thanks!

**Pull request merged**
