### PR TITLE
instrument the build with honeycomb buildevents

### PR DESCRIPTION
**Pull request by toshok**
Depends on a fork of the honeycomb buildevents repo [here](https://github.com/replayio/buildevents/tree/toshok/add-buildkite-watch) (which adds a buildkite-specific version of the `watch` command.) and the buildkite plugin [here](https://github.com/replayio/buildevents-buildkite-plugin).

No windows support yet (the ssm plugin has windows issues as well, but there are hamfisted batch files in the buildkite plugin) so those steps aren't instrumented.

Likewise the runtime e2e in the backend aren't instrumented currently, but there's a corresponding backend PR for that https://github.com/replayio/backend/pull/9038.

Both of those gaps in instrumentation are visible in build traces as .. big unexplained gaps in the root span.

### CODE REVIEW

**Review by jazzdan — APPROVED** [review]
This LGTM! I have a change in #971 that will conflict with this but I think I can update it to match what you're doing here.

Just curious: where is `be_cmd` defined?

**Comment by jazzdan** [comment]
Oh nvm I didn't look at the plugin.

**Comment by toshok** [comment]
oh yeah, I would also totally love some 👀 /opinions/bikeshedding on how things are done in the buildkite plugin.  was mostly riffing off what I'd seen elsewhere, and things like `be_cmd` save a whole bunch of repetition in the pipeline.

**Comment by jazzdan** [comment]
@toshok the plugin looks good to me but my bash knowledge is at like a 5th grade level 😂

**Pull request merged**
