### PR TITLE
Browser/Renderer bridge for passing replay events.

### PR DESCRIPTION
**Pull request by kannanvijayan**

### CODE REVIEW

**Comment by kannanvijayan** [comment]
There's some slight cruft in this patch, but it establishes a replay-specific communication between the browser and render processes.

I also think that the place in this patch where the "KvKvTestEvent" message is sent (`RenderProcessHostImpl::Init`), or its caller, is likely where we want to inject the browser-side logic.

I still need to wire the receiver end of this code in the render process to pipe the events into our `record_replay_interface.cc` code.

**Comment by kannanvijayan** [comment]
I'm trying to update this to link the renderer rr-message handling code to pipe things to the V8 code where we run our instrumentation, but running into various scoping and namespacing and linking issues.  I think that while blink and v8 live in the same process, their code is linked separately.

The approach I'm going with is to use a global callback function pointer in the content code, which is set by the V8 code.  The resolution should be to make the callback-installer function part of the public API of the blink codebase, and then use it from the v8 code.

**Comment by kannanvijayan** [comment]
Been trying to get this to work for the last couple hours, and the build still doesn't work right.. however, the build failure occurs when we're building `v8_context_snapshot_generator`.

Realized the problem is maybe because v8 can be built standalone, in which case we wouldn't pull in the blink code.  So really the dependency needs to go the other way: blink calls an API function within V8 to deliver the messages directly.

**Comment by kannanvijayan** [comment]
Ok this push works fine.  The comments mention typing the, but it's probably better to find a way to convert `base::Value` to a JSON `v8::Value` to pass into our javascript instrumentation.  We can't use `base::Value` because it's defined at a higher level (for content), and there are no existing uses of it in the v8 binding code at all.

**Comment by kannanvijayan** [comment]
Added the final bits to convert the data payload to `v8::Value` from`base::Value` and send it into the JS code for handling.  However, the browser is crashing somewhere later (somewhere in `cpp/recording/ProgressCounter.cpp`, where it asserts that a checkpoint has been created - apparently a progress counter is getting incremented despite the first checkpoint not having been created yet.

**Comment by kannanvijayan** [comment]
This should be good for review now.  The message pipeline from content down into the render process and our is instrumentation is implemented here.  Right now it terminates with a log message, but after we get the actual correct events flowing through we can fix that up to save the events and send them back to the controller.

**Review by bhackett1024 — APPROVED** [review]

**Comment by kannanvijayan** [comment]
Fixed up a bunch of cruft, but no semantic changes.

**Pull request merged**
