### PR TITLE
Assert PortLocker::PortLocker, Histogram::Factory::Build

### PR DESCRIPTION
**Pull request by Domiii**
* https://linear.app/replay/issue/RUN-1217#comment-ac993670
* https://linear.app/replay/issue/RUN-1310/asserts-for-portlockerportlocker-and-nominalcpufrequency

### CODE REVIEW

**Review by kannanvijayan — APPROVED** [review]

**Review by bhackett1024 — APPROVED** [review]
Looks good, though for assertions with multiple issues can we use a format like `[RUN-issue1-issue2]` ?  That would look a little better I think.

**Comment by kannanvijayan** [comment]
> Looks good, though for assertions with multiple issues can we use a format like `[RUN-issue1-issue2]` ? That would look a little better I think.

Note: Having `[RUN-issue1] [RUN-issue2]` would allow for better pickup in our automated admin systems.

**Comment by Domiii** [comment]
@bhackett1024 
> Looks good, though for assertions with multiple issues can we use a format like `[RUN-issue1-issue2]` ? That would look a little better I think.

That's what I said! Jason wanted `[RUN-X/Y]`.

The reason why it is like this is because our admin app is stupid and needs updating if we want to have the prettier version of the labels. I'll add an issue to the crash monitoring project.

@kannanvijayan 
> `[RUN-issue1] [RUN-issue2]`

I felt that that was too verbose :disappointed:

**Comment by kannanvijayan** [comment]
> 
> That's what I said! Jason wanted `[RUN-X/Y]`.

I think Jason was talking in that case about labeling assertions that were addressing a parent issue X, but where the child issue the PR was attached to was Y.  That's a nice to have eventually, but different from labeling a set of asserts that apply to multiple underlying crash buckets.

**Comment by Domiii** [comment]
> addressing a parent issue X, but where the child issue the PR was attached to was Y

What do you mean?

**Comment by kannanvijayan** [comment]
> > addressing a parent issue X, but where the child issue the PR was attached to was Y
> 
> What do you mean?

I'm talking about our approach of creating child issues for each of our buckets, and landing PRs under those child issues instead of under the issue for the bucket as a whole.  That's the case that Jason was addressing.

I think  @bhackett1024 misunderstood something here: that this PR doesn't address two separate buckets - it addresses one child issue (RUN-1310) for a parent bucket issue (RUN-1217), and happens to mention both in the comment.

**Pull request merged**
